{% set name = "autocombobox" %}
{% set version = "1.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autocombobox-{{ version }}.tar.gz
  sha256: b260d889ed896e07f8ce6fbd7618f73e61924b1f9c94d87611b281e3f93f4c0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - autocombobox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Church-17/autocombobox
  summary: Ttk widge that insert a Combobox into GUIs that allows suggestions based on what the user writes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
