{% set name = "autocombobox" %}
{% set version = "1.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autocombobox-{{ version }}.tar.gz
  sha256: 222d8c7332a46440933ff1031dd2ca5355f87de20e8d2cf5f7c17bcb438f9f8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - autocombobox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Church-17/autocombobox
  summary: Ttk widge that insert a Combobox into GUIs that allows suggestions based on what the user writes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
