schema_version: 1

context:
  name: autocombobox
  version: "1.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/autocombobox-${{ version }}.tar.gz
  sha256: 9ce31174582da5bb1e4fb40833d98044e86e4ca056cc8e5bdae0e30b715802a5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - autocombobox
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Ttk widge that insert a Combobox into GUIs that allows suggestions based on what the user writes
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/Church-17/autocombobox

extra:
  recipe-maintainers:
    - thewchan
